Repository pulumi/pulumi-eks, pull requests merged in 2019-06, with the labels that each got.

#143 Fix API doc markdown rendering issue
  nodejs/eks/cluster.ts
Labels: impact/no-changelog-required

#145 Update CHANGELOG to prep for v0.18.6
  CHANGELOG.md
Labels: impact/no-changelog-required

#147 Update k8s provider dependency to 0.24.0
  nodejs/eks/package.json
Labels: impact/no-changelog-required

#148 update(aws-k8s-cni): move from 1.4.1 -> 1.5.0
  CHANGELOG.md
  nodejs/eks/cni/aws-k8s-cni.yaml
Labels: customer/feedback, enhancement

#150 tests(cluster): enable test to replace cluster by adding more subnets
  CHANGELOG.md
  nodejs/eks/examples/all_test.go
Labels: testing

#161 Update CHANGELOG to prep for v0.18.7
  CHANGELOG.md
Labels: impact/no-changelog-required

#167 Miscellaneous cleanup
  nodejs/eks/cluster.ts
  nodejs/eks/nodegroup.ts
Labels: impact/no-changelog-required

#168 Use proxy to download Go deps
  build/common.mk
Labels: impact/no-changelog-required
