Repository pulumi/pulumi-eks, pull requests merged in 2019-05, with the labels that each got.

#133 fix(cluster): export missing instanceRoles in the cluster's CoreData
  CHANGELOG.md
  nodejs/eks/cluster.ts
Labels: bug

#131 Update link to aws-iam-authenticator install documents
  README.md
Labels: impact/no-changelog-required

#134 update(aws-k8s-cni): move from 1.3.0 -> 1.4.1
  CHANGELOG.md
  nodejs/eks/cni/aws-k8s-cni.yaml
Labels: update
