Repository pulumi/pulumi-eks, pull requests merged in 2019-09, with the labels that each got.

#245 fix(tests): temporarily disable tests with RunUpdateTest to fix master
  nodejs/eks/examples/all_test.go
  nodejs/eks/examples/examples_test.go
Labels: impact/no-changelog-required

#239 Add publicSubnetIds and privateSubnetIds cluster opts. Update tests to use new awsx.ec2.Vpc API and new subnet opts
  CHANGELOG.md
  nodejs/eks/cluster.ts
  nodejs/eks/examples/all_test.go
  nodejs/eks/examples/cluster/README.md
  nodejs/eks/examples/cluster/index.ts
  nodejs/eks/examples/tests/awsx-network-and-subnetIds/Pulumi.yaml
  nodejs/eks/examples/tests/awsx-network-and-subnetIds/README.md
  nodejs/eks/examples/tests/awsx-network-and-subnetIds/iam.ts
  nodejs/eks/examples/tests/awsx-network-and-subnetIds/index.ts
  nodejs/eks/examples/tests/awsx-network-and-subnetIds/package.json
  nodejs/eks/examples/tests/awsx-network-and-subnetIds/tsconfig.json
  nodejs/eks/examples/tests/migrate-nodegroups/index.ts
  nodejs/eks/examples/tests/replace-cluster-add-subnets/index.ts
  nodejs/eks/examples/tests/replace-cluster-add-subnets/step1/index.ts
  nodejs/eks/examples/tests/replace-secgroup/index.ts
  nodejs/eks/examples/tests/replace-secgroup/step1/index.ts
  nodejs/eks/nodegroup.ts
Labels: enhancement

#246 Prep for v0.18.14
  CHANGELOG.md
Labels: update

#250 Consume the build-package-docs script.
  Makefile
Labels: impact/no-changelog-required

#255 Fix `deprecated` tag
  nodejs/eks/cluster.ts
Labels: impact/no-changelog-required

#254 Sync `scripts/get-version` with pulumi/pulumi
  scripts/get-version
Labels: impact/no-changelog-required
